"""empty message

Revision ID: f9012a2cc9c1
Revises: 9097cdd00c51
Create Date: 2026-07-20 20:56:56.093373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9012a2cc9c1'
down_revision = '9097cdd00c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_shares', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('expense_shares_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('expense_shares_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'expenses', ['expense_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('expenses_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('expenses_ibfk_1'), 'groups', ['group_id'], ['id'])

    with op.batch_alter_table('expense_shares', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('expense_shares_ibfk_1'), 'expenses', ['expense_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('expense_shares_ibfk_2'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
